name 'puppetlabs-apache'
version '0.4.0'

author 'puppetlabs'
license 'Apache 2.0'
project_page 'https://github.com/puppetlabs/puppetlabs-apache'
source 'git://github.com/puppetlabs/puppetlabs-apache.git'
summary 'Puppet module for Apache'
description 'Module for Apache configuration'
dependency 'puppetlabs/firewall', '>=0.0.4'
dependency 'puppetlabs/stdlib', '>=2.2.1'
