name 'puppetlabs-keystone'
version '1.0.1'

author 'Puppet Labs'
license 'Apache'
project_page 'http://github.com/puppetlabs/puppetlabs-keystone'
source 'git://github.com/puppetlabs/puppetlabs-keystone'
summary 'Keystone Puppet Module'
description 'Openstack Folsom Keystone module. Tested on Ubuntu and RHEL 6'
dependency 'cprice404/inifile', '>=0.9.0'
dependency 'puppetlabs/mysql', '>=0.5.0'
dependency 'puppetlabs/stdlib', '==3.2.0'
dependency 'puppetlabs/postgresql', '==1.0.0'
dependency 'puppetlabs/vcsrepo', '==0.1.1'
